### ISSUE TITLE
sei un fallito

### ISSUE THREAD

**Issue by MafraReal** [dev-callum/Power-AC#1]
this cracked anticheat nothing works bruh hahahah

**Comment by dev-callum** [comment]
ITs not cracked, its the full source, I made it with a guy that tried to dox me, my functions work, his don't

**Comment by MafraReal** [comment]
in fact you are good at cheating bruh, shame on you suck


Il giorno mar 16 nov 2021 alle ore 22:23 Callum ***@***.***>
ha scritto:
